const authorize = require('./authorize');
const keys = require('./keys');
const metadata_endpoints = require('./metadata_endpoints');
const patient_service = require('./patient_service');
const patient_picker = require('./patient_picker');
const token_hook = require('./token_hook');
const token = require('./token');

exports.authorizeHandler = authorize.authorizeHandler;
exports.pickerCallbackHandler = authorize.pickerCallbackHandler;
exports.authorizeCallbackHandler = authorize.authorizeCallbackHandler;
exports.keysHandler = keys.keysHandler;
exports.smartConfigHandler = metadata_endpoints.smartConfigHandler;
exports.metadataHandler = metadata_endpoints.metadataHandler;
exports.PatientServiceHandler = patient_service.PatientServiceHandler;
exports.patientPickerGetHandler = patient_picker.patientPickerGetHandler;
exports.patientPickerPostHandler = patient_picker.patientPickerPostHandler;
exports.tokenHookHandler = token_hook.tokenHookHandler;
exports.tokenHandler = token.tokenHandler;
